title: Trial and Forget
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Trial and Error + Fire and Forget
baseurl: ""
url: ""
twitter_username: pekalicious
github_username:  pekalicious

# Build settings
kramdown:
  input: GFM
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed